/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fixedAsset;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ChibuezePaul
 */
public class AddAsset extends javax.swing.JFrame {

    /**
     * Creates new form AddAsset
     */
    String ref;

    public AddAsset() {
        initComponents();
        setLocationRelativeTo(JOptionPane.getRootFrame());
        this.setIconImage(new ImageIcon(getClass().getResource("Asset.png")).getImage());
        setID(ref);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panMachinery = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtMID = new javax.swing.JTextField();
        txtMItem = new javax.swing.JTextField();
        txtMULife = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtMSalvage = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtMCost = new javax.swing.JTextField();
        btnAddMahinery = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtMDepreciation = new javax.swing.JTextField();
        comMDate = new datechooser.beans.DateChooserCombo();
        panFurniture = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtFID = new javax.swing.JTextField();
        txtFItem = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtFSalvage = new javax.swing.JTextField();
        txtFULife = new javax.swing.JTextField();
        txtFCost = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        btnAddFurniture = new javax.swing.JButton();
        txtFDepreciation = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        comFDate = new datechooser.beans.DateChooserCombo();
        panBuilding = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtBID = new javax.swing.JTextField();
        txtBLocation = new javax.swing.JTextField();
        txtBCost = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAddBuilding = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        comBDate = new datechooser.beans.DateChooserCombo();
        panLand = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLID = new javax.swing.JTextField();
        txtLLocation = new javax.swing.JTextField();
        txtLCost = new javax.swing.JTextField();
        btnAddLand = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        comLDate = new datechooser.beans.DateChooserCombo();
        panVehicle = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtVID = new javax.swing.JTextField();
        txtVehicleNo = new javax.swing.JTextField();
        txtChasisNo = new javax.swing.JTextField();
        txtVCost = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEngineNo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtVULife = new javax.swing.JTextField();
        txtVSalvage = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        btnAddVehicle = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtVDepreciation = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        comVDate = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add New Asset");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buildings, Machinery, Vehicle, Furniture, etc...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel4.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Info_20px.png"))); // NOI18N
        jLabel4.setText("ISoft");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        panMachinery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panMachinery.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panMachineryComponentShown(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("ID Number");

        txtMID.setEditable(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Useful Life");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Date Acquired");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Item");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Salvage");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Cost");

        btnAddMahinery.setForeground(new java.awt.Color(0, 0, 0));
        btnAddMahinery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_20px.png"))); // NOI18N
        btnAddMahinery.setText("Add");
        btnAddMahinery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMahineryActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Tractor_50px_2.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Depreciation");

        javax.swing.GroupLayout panMachineryLayout = new javax.swing.GroupLayout(panMachinery);
        panMachinery.setLayout(panMachineryLayout);
        panMachineryLayout.setHorizontalGroup(
            panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMachineryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddMahinery)
                        .addGroup(panMachineryLayout.createSequentialGroup()
                            .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel22)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panMachineryLayout.createSequentialGroup()
                                    .addGap(120, 120, 120)
                                    .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMULife)
                                        .addComponent(txtMSalvage)
                                        .addComponent(txtMCost)
                                        .addComponent(txtMItem)
                                        .addComponent(txtMID)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMachineryLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMDepreciation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comMDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jLabel36))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        panMachineryLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comMDate, txtMULife});

        panMachineryLayout.setVerticalGroup(
            panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMachineryLayout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panMachineryLayout.createSequentialGroup()
                        .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panMachineryLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comMDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtMULife, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtMSalvage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtMCost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMachineryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtMDepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnAddMahinery)
                .addContainerGap())
        );

        panMachineryLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comMDate, txtMULife});

        jTabbedPane1.addTab("Machinery", panMachinery);

        panFurniture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panFurniture.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panFurnitureComponentShown(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Sofa_50px.png"))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("ID Number");

        txtFID.setEditable(false);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Item");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Date Acquired");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Useful Life");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Salvage");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Cost");

        btnAddFurniture.setForeground(new java.awt.Color(0, 0, 0));
        btnAddFurniture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_20px.png"))); // NOI18N
        btnAddFurniture.setText("Add");
        btnAddFurniture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFurnitureActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Depreciation");

        javax.swing.GroupLayout panFurnitureLayout = new javax.swing.GroupLayout(panFurniture);
        panFurniture.setLayout(panFurnitureLayout);
        panFurnitureLayout.setHorizontalGroup(
            panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFurnitureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddFurniture)
                        .addGroup(panFurnitureLayout.createSequentialGroup()
                            .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel40)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(120, 120, 120)
                            .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFULife, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFSalvage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFCost, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFItem, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFID, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comFDate, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel18))
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panFurnitureLayout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(txtFDepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );

        panFurnitureLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comFDate, txtFULife});

        panFurnitureLayout.setVerticalGroup(
            panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFurnitureLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panFurnitureLayout.createSequentialGroup()
                        .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panFurnitureLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comFDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtFULife, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtFSalvage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtFCost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panFurnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtFDepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnAddFurniture)
                .addContainerGap())
        );

        panFurnitureLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comFDate, txtFULife});

        jTabbedPane1.addTab("Furniture", panFurniture);

        panBuilding.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panBuilding.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panBuildingComponentShown(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID Number");

        txtBID.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Cost");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Date Acquired");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Location");

        btnAddBuilding.setForeground(new java.awt.Color(0, 0, 0));
        btnAddBuilding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_20px.png"))); // NOI18N
        btnAddBuilding.setText("Add");
        btnAddBuilding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBuildingActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Home_50px.png"))); // NOI18N

        javax.swing.GroupLayout panBuildingLayout = new javax.swing.GroupLayout(panBuilding);
        panBuilding.setLayout(panBuildingLayout);
        panBuildingLayout.setHorizontalGroup(
            panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuildingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuildingLayout.createSequentialGroup()
                        .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBCost)
                            .addComponent(txtBLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtBID)
                            .addComponent(comBDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddBuilding)
                        .addComponent(jLabel17)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        panBuildingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comBDate, txtBLocation});

        panBuildingLayout.setVerticalGroup(
            panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBuildingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtBLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuildingLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)
                        .addGroup(panBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtBCost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddBuilding))
                    .addComponent(comBDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        panBuildingLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comBDate, txtBLocation});

        jTabbedPane1.addTab("Building", panBuilding);

        panLand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panLand.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panLandComponentShown(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Location");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Date Acquired");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cost");

        txtLID.setEditable(false);

        btnAddLand.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_20px.png"))); // NOI18N
        btnAddLand.setText("Add");
        btnAddLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLandActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Land_Sales_50px.png"))); // NOI18N

        javax.swing.GroupLayout panLandLayout = new javax.swing.GroupLayout(panLand);
        panLand.setLayout(panLandLayout);
        panLandLayout.setHorizontalGroup(
            panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLandLayout.createSequentialGroup()
                        .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLCost)
                            .addComponent(txtLLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtLID)
                            .addComponent(comLDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddLand)
                        .addComponent(jLabel19)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        panLandLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comLDate, txtLLocation});

        panLandLayout.setVerticalGroup(
            panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLandLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addGroup(panLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtLCost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnAddLand))
                    .addComponent(comLDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        panLandLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comLDate, txtLLocation});

        jTabbedPane1.addTab("Land", panLand);

        panVehicle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panVehicle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panVehicleComponentShown(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ID Number");

        txtVID.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cost");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Chasis Number");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Vehicle Number");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Engine Number");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Salvage");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Useful Life");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Date Acquired");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Brand");

        btnAddVehicle.setForeground(new java.awt.Color(0, 0, 0));
        btnAddVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_20px.png"))); // NOI18N
        btnAddVehicle.setText("Add");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Sedan_50px.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Depreciation");

        javax.swing.GroupLayout panVehicleLayout = new javax.swing.GroupLayout(panVehicle);
        panVehicle.setLayout(panVehicleLayout);
        panVehicleLayout.setHorizontalGroup(
            panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddVehicle)
                    .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panVehicleLayout.createSequentialGroup()
                            .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comVDate, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVULife, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVSalvage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panVehicleLayout.createSequentialGroup()
                            .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(120, 120, 120)
                            .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtChasisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVCost, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVDepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panVehicleLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comVDate, txtBrand});

        panVehicleLayout.setVerticalGroup(
            panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVehicleLayout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtChasisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panVehicleLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel33))
                    .addGroup(panVehicleLayout.createSequentialGroup()
                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comVDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtVULife, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVSalvage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))))
                .addGap(8, 8, 8)
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtVCost, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtVDepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panVehicleLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comVDate, txtBrand});

        jTabbedPane1.addTab("Vehicle", panVehicle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ResultSet rs;
    PreparedStatement pst;

    public String setID(String ref) {

        int i = (4132 + (int) (Math.random() * 1215));
        this.ref = ref;
        ref += i + 2314;
        return ref;
    }

    public void addMachineryFurniture(String assetType, String Id, String item, String date, String uLife, String salavage, String cost) {

        if (cost.equals("") && item.equals("") && salavage.equals("") && uLife.equals("") && date.equals(comMDate.getDateFormat())) {
            JOptionPane.showMessageDialog(null, "Incomplete user details", "Asset Management", 2);
        } else if (cost.equals("") || item.equals("") || salavage.equals("") || uLife.equals("") || date.equals(comMDate.getDateFormat())) {
            JOptionPane.showMessageDialog(null, "Incomplete user details", "Asset Management", 2);
        } else {
            try {
//                Signup.initialiseTable("assets", "CREATE TABLE `assets` (\n"
//                        + "  `id` varchar(10) NOT NULL,\n"
//                        + "  `asset type` varchar(15) NULL,\n"
//                        + "  `item` varchar(50) NULL,\n"
//                        + "  `location` varchar(50) NULL,\n"
//                        + "  `date_acquired` varchar(50) NULL,\n"
//                        + "  `useful_life` doubl NULL,\n"
//                        + "  `salavage_value` double NULL,\n"
//                        + "  `vehicle_no` varchar(15) NULL,\n"
//                        + "  `chasis_no` varchar(50) NULL,\n"
//                        + "  `engine_no` varchar(50) NULL,\n"
//                        + "  `brand` varchar(50) NULL,\n"
//                        + "  `cost` double NULL,\n"
//                        + "  `depreciation` double NULL,\n"
//                        + "  PRIMARY KEY (`id`)\n"
//                        + ")");
                pst = Signup.connect().prepareStatement("INSERT INTO `assets`(`id`,`item`,`date_acquired`,`useful_life`,`salavage_value`,`cost`,"
                        + "`asset type`,`location`,`vehicle_no`,`chasis_no`,`engine_no`,`brand`)VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");

                pst.setString(1, Id);
                pst.setString(2, item);
                pst.setString(3, date);
                pst.setString(4, uLife);
                pst.setString(5, salavage);
                pst.setString(6, cost);
                pst.setString(7, assetType);
                pst.setString(8, null);
                pst.setString(9, null);
                pst.setString(10, null);
                pst.setString(11, null);
                pst.setString(12, null);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Asset Successfully Created", "Asset Management", JOptionPane.PLAIN_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    public void addBuildingLand(String assetType, String Id, String location, String date, String cost) {

        if (cost.equals("") && location.equals("") && date.equals(comMDate.getDateFormat())) {
            JOptionPane.showMessageDialog(null, "Incomplete user details", "Asset Management", 2);
        } else {
            try {
//                Signup.initialiseTable("assets", "CREATE TABLE `assets` (\n"
//                        + "  `id` varchar(10) NOT NULL,\n"
//                        + "  `asset type` varchar(15) NULL,\n"
//                        + "  `item` varchar(50) NULL,\n"
//                        + "  `location` varchar(50) NULL,\n"
//                        + "  `date_acquired` varchar(50) NULL,\n"
//                        + "  `useful_life` doubl NULL,\n"
//                        + "  `salavage_value` double NULL,\n"
//                        + "  `vehicle_no` varchar(15) NULL,\n"
//                        + "  `chasis_no` varchar(50) NULL,\n"
//                        + "  `engine_no` varchar(50) NULL,\n"
//                        + "  `brand` varchar(50) NULL,\n"
//                        + "  `cost` double NULL,\n"
//                        + "  `depreciation` double NULL,\n"
//                        + "  PRIMARY KEY (`id`)\n"
//                        + ")");
                pst = Signup.connect().prepareStatement("INSERT INTO `fixedasset`.`assets`(`id`,`location`,`date_acquired`,`cost`,"
                        + "`asset type`,`useful_life`,`salavage_value`,`item`,`vehicle_no`,`chasis_no`,`engine_no`,`brand`)"
                        + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");

                pst.setString(1, Id);
                pst.setString(2, location);
                pst.setString(3, date);
                pst.setString(4, cost);
                pst.setString(5, assetType);
                pst.setString(6, null);
                pst.setString(7, null);
                pst.setString(8, null);
                pst.setString(9, null);
                pst.setString(10, null);
                pst.setString(11, null);
                pst.setString(12, null);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Asset Successfully Created", "Asset Management", JOptionPane.PLAIN_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    private void btnAddMahineryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMahineryActionPerformed
        addMachineryFurniture("Machinery", txtMID.getText(), txtMItem.getText(), (String.valueOf(comMDate.getSelection())), txtMULife.getText(), txtMSalvage.getText(), txtMCost.getText());
        txtMID.setText(null);
        txtMItem.setText(null);
        txtMULife.setText(null);
        txtMSalvage.setText(null);
        comMDate.setCurrent(comMDate.getCurrent());
        txtMCost.setText(null);
    }//GEN-LAST:event_btnAddMahineryActionPerformed

    private void btnAddBuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBuildingActionPerformed
        addBuildingLand("Building", txtBID.getText(), txtBLocation.getText(), (String.valueOf(comBDate.getSelection())), txtBCost.getText());
        txtBID.setText(null);
        txtBLocation.setText(null);
        txtBCost.setText(null);
        comBDate.setCurrent(comBDate.getCurrent());
    }//GEN-LAST:event_btnAddBuildingActionPerformed

    private void btnAddLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLandActionPerformed
        addBuildingLand("Building", txtLID.getText(), txtLLocation.getText(), (String.valueOf(comLDate.getSelection())), txtLCost.getText());
        txtLID.setText(null);
        txtLLocation.setText(null);
        txtLCost.setText(null);
        comLDate.setCurrent(comLDate.getCurrent());
    }//GEN-LAST:event_btnAddLandActionPerformed

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        if (txtVULife.getText().equals("") && txtVSalvage.getText().equals("") && txtVCost.getText().equals("") && txtVehicleNo.getText().equals("") && comVDate.getSelection().equals(comMDate.getDateFormat()) && txtChasisNo.getText().equals("") && txtEngineNo.getText().equals("") && txtBrand.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Incomplete user details", "Asset Management", 2);
        } else if (txtVULife.getText().equals("") || txtVSalvage.getText().equals("") || txtVCost.getText().equals("") || txtVehicleNo.getText().equals("") || comVDate.getSelection().equals(comMDate.getDateFormat()) || txtChasisNo.getText().equals("") || txtEngineNo.getText().equals("") || txtBrand.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Incomplete user details", "Asset Management", 2);
        } else {
            try {
//                Signup.initialiseTable("assets", "CREATE TABLE `assets` (\n"
//                        + "  `id` varchar(10) NOT NULL,\n"
//                        + "  `asset type` varchar(15) NULL,\n"
//                        + "  `item` varchar(50) NULL,\n"
//                        + "  `location` varchar(50) NULL,\n"
//                        + "  `date_acquired` varchar(50) NULL,\n"
//                        + "  `useful_life` doubl NULL,\n"
//                        + "  `salavage_value` double NULL,\n"
//                        + "  `vehicle_no` varchar(15) NULL,\n"
//                        + "  `chasis_no` varchar(50) NULL,\n"
//                        + "  `engine_no` varchar(50) NULL,\n"
//                        + "  `brand` varchar(50) NULL,\n"
//                        + "  `cost` double NULL,\n"
//                        + "  `depreciation` double NULL,\n"
//                        + "  PRIMARY KEY (`id`)\n"
//                        + ")");
                pst = Signup.connect().prepareStatement("INSERT INTO `fixedasset`.`assets`(`id`,`item`,`date_acquired`,`useful_life`,`salavage_value`,`cost`,"
                        + "`asset type`,`location`,`vehicle_no`,`chasis_no`,`engine_no`,`brand`)VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");

                pst.setString(1, txtVID.getText());
                pst.setString(2, null);
                pst.setString(3, (String.valueOf(comVDate.getSelection())));
                pst.setString(4, txtVULife.getText());
                pst.setString(5, txtVSalvage.getText());
                pst.setString(6, txtVCost.getText());
                pst.setString(7, "Vehicle");
                pst.setString(8, null);
                pst.setString(9, txtVehicleNo.getText());
                pst.setString(10, txtChasisNo.getText());
                pst.setString(11, txtEngineNo.getText());
                pst.setString(12, txtBrand.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Asset Successfully Created", "Asset Management", JOptionPane.PLAIN_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        txtVID.setText(null);
        txtVULife.setText(null);
        txtVCost.setText(null);
        txtVSalvage.setText(null);
        txtVehicleNo.setText(null);
        txtChasisNo.setText(null);
        txtEngineNo.setText(null);
        txtBrand.setText(null);
        comVDate.setCurrent(comVDate.getCurrent());
    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnAddFurnitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFurnitureActionPerformed
        addMachineryFurniture("Furniture", txtFID.getText(), txtFItem.getText(), (String.valueOf(comFDate.getSelection())), txtFULife.getText(), txtFSalvage.getText(), txtFCost.getText());
        txtFID.setText(null);
        txtFItem.setText(null);
        txtFULife.setText(null);
        txtFSalvage.setText(null);
        comFDate.setCurrent(comFDate.getCurrent());
        txtFCost.setText(null);
    }//GEN-LAST:event_btnAddFurnitureActionPerformed

    private void panFurnitureComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panFurnitureComponentShown
        this.ref = "F";
        txtFID.setText(setID(ref));
    }//GEN-LAST:event_panFurnitureComponentShown

    private void panMachineryComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panMachineryComponentShown
        this.ref = "M";
        txtMID.setText(setID(ref));
    }//GEN-LAST:event_panMachineryComponentShown

    private void panBuildingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panBuildingComponentShown
        this.ref = "B";
        txtBID.setText(setID(ref));
    }//GEN-LAST:event_panBuildingComponentShown

    private void panLandComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panLandComponentShown
        this.ref = "L";
        txtLID.setText(setID(ref));
    }//GEN-LAST:event_panLandComponentShown

    private void panVehicleComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panVehicleComponentShown
        this.ref = "V";
        txtVID.setText(setID(ref));
    }//GEN-LAST:event_panVehicleComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Confirm if you want to exit", "Ticket Booking",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            this.dispose();
            Assets.main(null);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAsset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBuilding;
    private javax.swing.JButton btnAddFurniture;
    private javax.swing.JButton btnAddLand;
    private javax.swing.JButton btnAddMahinery;
    private javax.swing.JButton btnAddVehicle;
    private datechooser.beans.DateChooserCombo comBDate;
    private datechooser.beans.DateChooserCombo comFDate;
    private datechooser.beans.DateChooserCombo comLDate;
    private datechooser.beans.DateChooserCombo comMDate;
    private datechooser.beans.DateChooserCombo comVDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panBuilding;
    private javax.swing.JPanel panFurniture;
    private javax.swing.JPanel panLand;
    private javax.swing.JPanel panMachinery;
    private javax.swing.JPanel panVehicle;
    private javax.swing.JTextField txtBCost;
    private javax.swing.JTextField txtBID;
    private javax.swing.JTextField txtBLocation;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtChasisNo;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtFCost;
    private javax.swing.JTextField txtFDepreciation;
    private javax.swing.JTextField txtFID;
    private javax.swing.JTextField txtFItem;
    private javax.swing.JTextField txtFSalvage;
    private javax.swing.JTextField txtFULife;
    private javax.swing.JTextField txtLCost;
    private javax.swing.JTextField txtLID;
    private javax.swing.JTextField txtLLocation;
    private javax.swing.JTextField txtMCost;
    private javax.swing.JTextField txtMDepreciation;
    private javax.swing.JTextField txtMID;
    private javax.swing.JTextField txtMItem;
    private javax.swing.JTextField txtMSalvage;
    private javax.swing.JTextField txtMULife;
    private javax.swing.JTextField txtVCost;
    private javax.swing.JTextField txtVDepreciation;
    private javax.swing.JTextField txtVID;
    private javax.swing.JTextField txtVSalvage;
    private javax.swing.JTextField txtVULife;
    private javax.swing.JTextField txtVehicleNo;
    // End of variables declaration//GEN-END:variables
}
